### ISSUE TITLE
can't find project 

### ISSUE THREAD

**Issue by alpa99** [appculture/xcode-project-renamer#1]
as far as I understood I have to navigate inside my project folder and use all the commands inside the folder. Doing so I get following error: 

<img width="590" alt="bildschirmfoto 2018-06-05 um 00 12 14" src="https://user-images.githubusercontent.com/29914517/40944717-188a7d82-6856-11e8-93b9-2dbc5ae034dc.png">

**Comment by tadija** [comment]
I think you should just use "Alpha" instead of "$Alpha", also new name should be without "$".
