### ISSUE TITLE
Project Name with Spaces

### ISSUE THREAD

**Issue by isadon** [appculture/xcode-project-renamer#11]
Are spaces supported in project names? It seems spaces are discarded when using this script.

**Comment by tadija** [comment]
you're right, spaces are indeed [removed from the new name](https://github.com/tadija/xcode-project-renamer/blob/f90fcb69c1316e2cdac7f3ad8ac3e13d758eb607/Sources/main.swift#L151) - i guess that was a workaround for some issue

**Comment by isadon** [comment]
I just started looking at the source code but maybe you can document what the issue with spaces is here?

**Comment by tadija** [comment]
tbh, i don't remember, but you can try it out, just remove the workaround part from the script and see what happens?

**Comment by isadon** [comment]
Yup 🙂. Will do. Thanks for the script btw, aside from this spaces issue it worked perfectly.

**Comment by tadija** [comment]
np, if you manage to fix the "spaces issue" reliably, feel free to send a PR

**Comment by isadon** [comment]
So the issue is how to do deal with `.swift` files and project files such as `pbxproj` which contain types or fields which reference the project name but are not allowed to have spaces. So for example renaming a project `Skeleton` to `New Project` there might be swift files which reference `Skeleton` as such `class Skeleton`. In the old non-renamed project these are fine but as soon as you try to rename the project `class New Project` is not valid. The pbxproj file also sees similar issues where various fields like `path=` fields are not allowed to have spaces but will with a simple rename.

Some work can definitely be put in to fix this issue but I'm definitely a bit short on time right now 🙂. For now I'll stick to a name without spaces in the rename. Maybe I can cook up PR some time later if no one beats me to it, might take a while though..

**Comment by tadija** [comment]
oh i see, yeah i remember now, it was much safer to just disable spaces in the new project name vs making it to work reliably (ie. to have the space in some cases but also not in some other cases)

anyway, i honestly don't see a big value in having the project name with spaces in the first place 🤷‍♂️
