### ISSUE TITLE
Pods don't work anymore

### ISSUE THREAD

**Issue by alpa99** [appculture/xcode-project-renamer#2]
Hi, 
I renamed my project and after that I did pod install and pod update. But my pods are still not working anymore any suggestions why ?

**Comment by tadija** [comment]
hmm, not really sure, try `pod deintegrate`, then `pod install`?

**Comment by AmitaiB** [comment]
That worked for me. @tadija, would it be troublesome to have the script run those two commands automatically, if a Pods directory is found?

**Comment by tadija** [comment]
I don't think that part belongs to this script, CocoaPods are not part of every project and they also have a dedicated command line tool for executing these commands.
