### ISSUE TITLE
Did not rename ObjC's Swift-code-import-header

### ISSUE THREAD

**Issue by AmitaiB** [appculture/xcode-project-renamer#6]
In ObjC files that import Swift code, is it possible to have it change:
`#import <$(OLD_NAME)-Swift.h>` to
`#import <$(NEW_NAME)-Swift.h>` **?**

**Comment by tadija** [comment]
The script literally goes through (almost) all the files in a directory and replaces all instances of "OLD_NAME" to "NEW_NAME" within content of each file, so the simple answer is: yes, it's possible.

**Comment by AmitaiB** [comment]
Thank you. For me, that is the only thing it misses. Does it work on those import statements for you?
